apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/database/deployment.yaml
  - k8s/database/service.yaml
  - k8s/database/pvc.yaml
  - k8s/backend/deployment.yaml
  - k8s/backend/service.yaml
  - k8s/frontend/deployment.yaml
  - k8s/frontend/service.yaml
  - k8s/ingress.yaml

secretGenerator:
- name: db-credentials
  envs:
    - .env

configMapGenerator:
- name: db-init-script
  files:
    - init_script.sql=setup/init_script.sql