apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - secretRef:
            name: db-credentials
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init_script.sql
          subPath: init_script.sql
          readOnly: true
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: db-init-script